const {randomKey,randomAccessCode,isAccessCode,roomKeyFromAccessCode,importRoomKey,encrypt,decrypt,deriveVaultKey,toB64,generateAdminKeyPair,importAdminPublicKey,importAdminPrivateKey,wrapRoomKey,unwrapRoomKey}=await import('../src/crypto.js');
const accessCode=randomAccessCode();
if(!isAccessCode(accessCode)||accessCode.length!==32)throw new Error('access code format failed');
if(accessCode===randomAccessCode())throw new Error('access code randomness failed');
const derived=await roomKeyFromAccessCode(accessCode);
if(derived!==await roomKeyFromAccessCode(accessCode)||derived.length!==43)throw new Error('access code key derivation failed');
let weakRejected=false;try{await roomKeyFromAccessCode('NIGHT4729')}catch{weakRejected=true}if(!weakRejected)throw new Error('weak code accepted for key derivation');
const raw=randomKey();
const key=await importRoomKey(raw);
const cipher=await encrypt(key,'<script>plain text only</script>\nsecond line','room-id');
if(await decrypt(key,cipher,'room-id')!=='<script>plain text only</script>\nsecond line')throw new Error('round trip failed');
let rejected=false;try{await decrypt(key,{...cipher,data:cipher.data.slice(0,-2)+'xx'},'room-id')}catch{rejected=true}if(!rejected)throw new Error('tamper not rejected');
const salt=toB64(crypto.getRandomValues(new Uint8Array(24)));
const vault=await deriveVaultKey('a strong host password',salt);
const wrapped=await encrypt(vault,raw);
if(await decrypt(vault,wrapped)!==raw)throw new Error('vault wrap failed');
const pair=await generateAdminKeyPair();
const publicKey=await importAdminPublicKey(pair.publicJwk);
const privateKey=await importAdminPrivateKey(pair.privateJwk);
const adminWrapped=await wrapRoomKey(publicKey,raw);
if(await unwrapRoomKey(privateKey,adminWrapped)!==raw)throw new Error('admin wrap failed');
const privateCipher=await encrypt(vault,JSON.stringify(pair.privateJwk),'kitty-admin-private-key-v1');
if(JSON.parse(await decrypt(vault,privateCipher,'kitty-admin-private-key-v1')).kty!=='RSA')throw new Error('private key vault failed');
console.log('PASS: AES-GCM encryption, tamper detection, password vault, and RSA room-key wrapping.');
